localstack:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/localstack/localstack:0.12.5"
  environment:
    - SERVICES=sqs
  ports:
    - "4566:4566"
dynamodb:
  image: "public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local"
  ports:
    - "45678:8000"
elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch:8.3.3"
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    - "http.host=0.0.0.0"
    - "transport.host=0.0.0.0"
    - "cluster.name=wellcome"
    - "discovery.type=single-node"
    - "xpack.security.enabled=false"
