[project]
name = "id-minter-scripts"
version = "0.1.0"
description = "Utility script(s) for local Step Function id minter testing"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
  "requests>=2.32.0,<3.0.0",
]

[tool.uv]
package = false