services:
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
  build:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - ../../.lambda_zips:/target
