services:
  test:
    build:
      context: .
      dockerfile: ../../builds/test.python.Dockerfile
    command: ["py.test"]
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=platform-developer
      - OUTPUT_TOPIC_ARN=${OUTPUT_TOPIC_ARN}
      - CUSTOMER_ID=${CUSTOMER_ID}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PREFIX=${S3_PREFIX}
      - FTP_SERVER=${FTP_SERVER}
      - FTP_USERNAME=${FTP_USERNAME}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - FTP_REMOTE_DIR=${FTP_REMOTE_DIR}
    command: ["python", "main.py"]
  publish:
    build:
      context: .
      dockerfile: ./Dockerfile
