# Note: this file is autogenerated with ./run_terraform.sh init.
#
# Edits to this file may be reverted!

locals {
  pipeline_date   = "2026-07-03"
  es_cluster_date = "2026-07-03"
}

terraform {
  backend "s3" {
    assume_role = {
      role_arn = "arn:aws:iam::760097843905:role/platform-developer"
    }

    bucket         = "wellcomecollection-platform-infra"
    key            = "terraform/catalogue-pipeline/pipeline/2026-07-03.tfstate"
    dynamodb_table = "terraform-locktable"
    region         = "eu-west-1"
  }
}
