version: '3.3'

services:
  localstack:
    image: "public.ecr.aws/localstack/localstack:3.5.0"
    environment:
      - SERVICES=sqs
      - ALLOW_NONSTANDARD_REGIONS=1
    ports:
      - "4566:4566"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.4.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=0.0.0.0"
      - "cluster.name=wellcome"
      - "logger.level=DEBUG"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "action.auto_create_index=false"
