# Run locally using `docker compose build lambda && docker compose run --rm  --service-ports lambda`
services:
  lambda:
    build:
      context: .
      dockerfile: Dockerfile
      target: lambda_rie
    volumes:
      - ~/.aws:/root/.aws
    ports:
      - "9000:8080"
    environment:
      - AWS_PROFILE=platform-developer
      - metrics_namespace=catalogue-dev_relation_embedder
      - affected_works_scroll_size=50
      - complete_tree_scroll_size=800
      - index_batch_size=100
      - index_flush_interval_seconds=60
      - es_protocol=https
      - es_port=443
    env_file:
      - .env
