name: 'Python Docker'
description: "Builds and publishes a Docker image"
inputs:
  folder:
    description: "working folder"
    required: true
  target:
    description: "target of a multistage build"
    required: true
  tag:
    description: "tag for the image"
    required: true
  role_to_assume:
    description: "role to assume when "
    required: true
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        role-to-assume: ${{ inputs.role_to_assume }}

    - name: build docker image
      run: |
        docker build . --build-arg pythonversion=$(cat .python-version) --tag "${{inputs.target}}:${{inputs.tag}}" --target "${{inputs.target}}"
      working-directory: ${{inputs.folder}}
      shell: bash

    - name: publish versioned container to registry
      uses: ./.github/actions/push_to_ecr
      with:
        registry: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome
        image_name: ${{inputs.target}}
        local_tag: ${{inputs.tag}}
        registry_tag: ${{inputs.tag}}

    - name: publish latest container to registry
      uses: ./.github/actions/push_to_ecr
      with:
        if: ${{ github.ref == 'refs/heads/main' }}
        registry: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome
        image_name: ${{inputs.target}}
        local_tag: ${{inputs.tag}}
        registry_tag: latest