import os

NEPTUNE_CLUSTER_IDENTIFIER_DEFAULT = "catalogue-graph"
NEPTUNE_CLUSTER_IDENTIFIER = os.environ.get(
    "NEPTUNE_CLUSTER_IDENTIFIER", NEPTUNE_CLUSTER_IDENTIFIER_DEFAULT
)

GRAPH_QUERIES_SNS_TOPIC_ARN = os.environ.get("GRAPH_QUERIES_SNS_TOPIC_ARN")

LOC_SUBJECT_HEADINGS_URL = (
    "https://id.loc.gov/download/authorities/subjects.madsrdf.jsonld.gz"
)
LOC_NAMES_URL = "https://id.loc.gov/download/authorities/names.madsrdf.jsonld.gz"
MESH_URL = "https://nlmpubs.nlm.nih.gov/projects/mesh/MESH_FILES/xmlmesh/desc2025.gz"
WIKIDATA_SPARQL_URL = "https://query.wikidata.org/sparql"

SLACK_SECRET_ID = os.environ.get("SLACK_SECRET_ID", "")

CATALOGUE_GRAPH_S3_BUCKET_DEFAULT = "wellcomecollection-catalogue-graph"
CATALOGUE_GRAPH_S3_BUCKET = os.environ.get(
    "CATALOGUE_GRAPH_S3_BUCKET", CATALOGUE_GRAPH_S3_BUCKET_DEFAULT
)

INGESTOR_S3_PREFIX_DEFAULT = "ingestor"
INGESTOR_S3_PREFIX = os.environ.get("INGESTOR_S3_PREFIX", INGESTOR_S3_PREFIX_DEFAULT)

BULK_LOADER_S3_PREFIX_DEFAULT = "graph_bulk_loader"
BULK_LOADER_S3_PREFIX = os.environ.get(
    "BULK_LOADER_S3_PREFIX", BULK_LOADER_S3_PREFIX_DEFAULT
)

GRAPH_REMOVER_S3_PREFIX_DEFAULT = "graph_remover"
GRAPH_REMOVER_S3_PREFIX = os.environ.get(
    "GRAPH_REMOVER_S3_PREFIX", GRAPH_REMOVER_S3_PREFIX_DEFAULT
)

INCREMENTAL_GRAPH_REMOVER_S3_PREFIX_DEFAULT = "graph_remover_incremental"
INCREMENTAL_GRAPH_REMOVER_S3_PREFIX = os.environ.get(
    "INCREMENTAL_GRAPH_REMOVER_S3_PREFIX", INCREMENTAL_GRAPH_REMOVER_S3_PREFIX_DEFAULT
)

INGESTOR_SHARD_SIZE_DEFAULT = 10000
INGESTOR_SHARD_SIZE = int(
    os.environ.get("INGESTOR_SHARD_SIZE", INGESTOR_SHARD_SIZE_DEFAULT)
)
INGESTOR_PIPELINE_DATE = os.environ.get("INGESTOR_PIPELINE_DATE")

ES_MERGED_INDEX_NAME = "works-denormalised"

ES_SOURCE_PARALLELISM = 5
ES_SOURCE_SLICE_COUNT = 30
ES_SOURCE_BATCH_SIZE = 2000

## Local Elasticsearch Configuration
ES_LOCAL_HOST = os.environ.get("ES_LOCAL_HOST")
ES_LOCAL_PORT = os.environ.get("ES_LOCAL_PORT")
ES_LOCAL_SCHEME = os.environ.get("ES_LOCAL_SCHEME")
ES_LOCAL_API_KEY = os.environ.get("ES_LOCAL_API_KEY")
