ROOT = $(shell git rev-parse --show-toplevel)
include $(ROOT)/makefiles/functions.Makefile

STACK_ROOT = mets_adapter

PROJECT_ID = mets_adapter

SBT_APPS = mets_adapter
SBT_NO_DOCKER_APPS =

SBT_DOCKER_LIBRARIES =
SBT_NO_DOCKER_LIBRARIES =

PYTHON_APPS =
LAMBDAS =

$(val $(call stack_setup))
