ROOT = $(shell git rev-parse --show-toplevel)
include $(ROOT)/makefiles/functions.Makefile

STACK_ROOT = tei_adapter

PROJECT_ID = tei_adapter

SBT_APPS =
SBT_NO_DOCKER_APPS =

SBT_DOCKER_LIBRARIES =
SBT_NO_DOCKER_LIBRARIES =

PYTHON_APPS =
LAMBDAS =

$(val $(call stack_setup))
