s3:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/scality/s3server:mem-latest"
  ports:
    - "33333:8000"
localstack:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/localstack/localstack"
  environment:
    - SERVICES=sqs
  ports:
    - "4566:4566"
