version: '3.3'
services:
  s3:
    image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/zenko/cloudserver:8.1.8"
    environment:
      - "S3BACKEND=mem"
    ports:
      - "33333:8000"
  localstack:
    image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/localstack/localstack:0.12.5"
    environment:
      - SERVICES=sqs
    ports:
      - "4566:4566"
