# Note: this file is autogenerated by the run_terraform.sh script.
#
# Edits to this file may be reverted!

locals {
  pipeline_date = "2025-05-01"
}

terraform {
  backend "s3" {
    assume_role = {
      role_arn = "arn:aws:iam::760097843905:role/platform-developer"
    }

    bucket         = "wellcomecollection-platform-infra"
    key            = "terraform/catalogue-pipeline/pipeline/2025-03-06.tfstate"
    dynamodb_table = "terraform-locktable"
    region         = "eu-west-1"
  }
}
