steps:
  - label: deploy CALM adapter
    plugins:
      - docker#v3.5.0:
          image: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.7
          workdir: /repo
          mount-ssh-agent: true
          command: [
              "--project-id", "calm_adapter",
              "--confirm",
              "release-deploy",
              "--from-label", "ref.$BUILDKITE_COMMIT",
              "--environment-id", "prod",
              "--description", $BUILDKITE_BUILD_URL,
              "--confirmation-wait-for", 3600]
    agents:
      queue: nano
  - label: deploy METS adapter
    plugins:
      - docker#v3.5.0:
          image: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.7
          workdir: /repo
          mount-ssh-agent: true
          command: [
              "--project-id", "mets_adapter",
              "--confirm",
              "release-deploy",
              "--from-label", "ref.$BUILDKITE_COMMIT",
              "--environment-id", "prod",
              "--description", $BUILDKITE_BUILD_URL,
              "--confirmation-wait-for", 3600]
    agents:
      queue: nano
  - label: deploy Sierra adapter
    plugins:
      - docker#v3.5.0:
          image: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.7
          workdir: /repo
          mount-ssh-agent: true
          command: [
              "--project-id", "sierra_adapter",
              "--confirm",
              "release-deploy",
              "--from-label", "ref.$BUILDKITE_COMMIT",
              "--environment-id", "prod",
              "--description", $BUILDKITE_BUILD_URL,
              "--confirmation-wait-for", 3600]
    agents:
      queue: nano
  - label: deploy TEI adapter
    plugins:
      - docker#v3.5.0:
          image: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.7
          workdir: /repo
          mount-ssh-agent: true
          command: [
              "--project-id", "tei_adapter",
              "--confirm",
              "release-deploy",
              "--from-label", "ref.$BUILDKITE_COMMIT",
              "--environment-id", "prod",
              "--description", $BUILDKITE_BUILD_URL,
              "--confirmation-wait-for", 3600]
    agents:
      queue: nano
  - label: deploy reindexer
    plugins:
      - docker#v3.5.0:
          image: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.7
          workdir: /repo
          mount-ssh-agent: true
          command: [
              "--project-id", "reindexer",
              "--confirm",
              "release-deploy",
              "--from-label", "ref.$BUILDKITE_COMMIT",
              "--environment-id", "prod",
              "--description", $BUILDKITE_BUILD_URL,
              "--confirmation-wait-for", 3600]
    agents:
      queue: nano
