steps:
  - label: "run matcher ({{ matrix }})"
    command: |
      ./builds/run_sbt_tests.sh matcher

    matrix:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"

    agents:
      queue: "scala"
