name: "Retag Docker Image"
description: "Retags an existing Docker image in ECR with a new tag"
inputs:
  registry:
    description: "ECR registry where the image is located"
    required: true
  image_name:
    description: "Name of the image to retag"
    required: true
  source_tag:
    description: "Existing tag of the image to retag"
    required: true
  target_tag:
    description: "New tag to apply to the image"
    required: true
  role_to_assume:
    description: "Role to assume when accessing ECR"
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        role-to-assume: ${{ inputs.role_to_assume }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Retag image
      shell: bash
      run: |
        echo "Pulling: $SOURCE_FULLNAME"
        docker pull "$SOURCE_FULLNAME"
        echo "Tagging: $SOURCE_FULLNAME -> $TARGET_FULLNAME"
        docker tag "$SOURCE_FULLNAME" "$TARGET_FULLNAME"
        echo "Pushing: $TARGET_FULLNAME"
        docker push "$TARGET_FULLNAME"
      env:
        SOURCE_FULLNAME: "${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.source_tag }}"
        TARGET_FULLNAME: "${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.target_tag }}"
