module "images_pipeline" {
  source                               = "../modules/image_pipeline"
  namespace                            = local.namespace
  namespace_hyphen                     = local.namespace_hyphen
  dlq_alarm_arn                        = var.dlq_alarm_arn
  merger_images_topic_arn              = module.merger_images_topic.arn
  aws_security_group_service_egress_id = aws_security_group.service_egress.id
  ec_privatelink_security_group_id     = var.ec_privatelink_security_group_id
  aws_ecs_cluster_cluster_name         = aws_ecs_cluster.cluster.name
  aws_ecs_cluster_cluster_arn          = aws_ecs_cluster.cluster.arn
  inference_capacity_provider_name     = module.inference_capacity_provider.name
  inference_manager_image              = local.inference_manager_image
  feature_inferrer_image               = local.feature_inferrer_image
  lsh_model_key                        = local.lsh_model_key
  inferrer_model_data_bucket_name      = var.inferrer_model_data_bucket_name
  palette_inferrer_image               = local.palette_inferrer_image
  aspect_ratio_inferrer_image          = local.aspect_ratio_inferrer_image
  es_images_initial_index              = local.es_images_initial_index
  es_images_augmented_index            = local.es_images_augmented_index
  pipeline_storage_es_service_secrets  = local.pipeline_storage_es_service_secrets["inferrer"]
  subnets                              = var.subnets
  min_capacity                         = var.min_capacity
  max_capacity                         = var.max_capacity
  scale_down_adjustment                = local.scale_down_adjustment
  scale_up_adjustment                  = local.scale_up_adjustment
  release_label                        = var.release_label
  shared_logging_secrets               = var.shared_logging_secrets
}