name: 'Push to ECR'
description: "Pushes a Docker image to an amazon ECR repository"
inputs:
  registry:
    description: "URL of registry where the image will be pushed"
    required: true
  image_name:
    description: "Name of the image to push"
    required: true
  local_tag:
    description: "Tag of the local image"
    required: true
  registry_tag:
    description: "Tag to be used for the image on the registry"
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Push to ECR
      shell: bash
      run: |
        docker tag "$LOCAL_FULLNAME" "$TARGET_FULLNAME"
        docker push $TARGET_FULLNAME
      env:
        TARGET_FULLNAME: "${{inputs.registry}}/${{inputs.image_name}}:${{inputs.registry_tag}}"
        LOCAL_FULLNAME: "${{inputs.image_name}}:${{inputs.local_tag}}"