name: 'Push to ECR'
inputs:
  registry:
    description: "URL of registry where the image will be pushed"
    required: true
  image_name:
    description: "Name of the image to push"
    required: true
  local_tag:
    description: "Tag of the local image"
    required: true
  registry_tag:
    description: "Tag to be used for the image on the registry, defaults to same as local"
    required: false
    default: ${{inputs.local_tag}}
runs:
  using: "composite"
  steps:
    - name: Push to ECR
      shell: bash
      run: |
        TARGET_FULLNAME="${{inputs.registry}}/${{inputs.image_name}}:${{inputs.registry_tag}}"
        docker tag "${{inputs.image_name}}:${{inputs.local_tag}}" "$TARGET_FULLNAME"
        docker push $TARGET_FULLNAME