addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.35")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.5")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.22.0")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.3.2")
