services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3307:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=password"
  localstack:
    image: "localstack/localstack:3.5.0"
    environment:
      - SERVICES=sqs
      - ALLOW_NONSTANDARD_REGIONS=1
    ports:
      - "4566:4566"
