mysql:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/library/mysql:5.6"
  ports:
    - "3307:3306"
  environment:
      - "MYSQL_ROOT_PASSWORD=password"
localstack:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/localstack/localstack"
  environment:
    - SERVICES=sqs
  ports:
    - "4566:4566"
