# Run locally using `docker compose build lambda && docker compose run --rm  --service-ports lambda`
services:
  lambda:
    build:
      context: .
      dockerfile: Dockerfile
      target: lambda_rie
    volumes:
      - ~/.aws:/root/.aws
    ports:
      - "9000:8080"
    environment:
      - AWS_PROFILE=platform-developer
      - metrics_namespace=catalogue-dev_batcher
      - use_downstream=stdio
