name: "Run integration tests"
description: "Runs integration tests against the catalogue graph database"
inputs:
  role_to_assume:
    description: "Role to assume when running integration tests"
    required: true
  slack_webhook_secret_id:
    description: "Secrets Manager secret id/name for the Slack failure alert webhook"
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        role-to-assume: ${{ inputs.role_to_assume }}
    - uses: actions/setup-python@v5
      with:
        python-version-file: catalogue_graph/.python-version
    - name: setup dependencies
      run: |
        pip install uv
        uv sync --all-groups
      working-directory: catalogue_graph
      shell: bash
    - name: test
      run: |
        uv run pytest -m "integration"
      working-directory: catalogue_graph
      shell: bash

    - name: Get Slack webhook URL
      if: ${{ failure() }}
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          SLACK_WEBHOOK_URL,${{ inputs.slack_webhook_secret_id }}

    - name: Notify Slack on failure
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v2.1.1
      with:
        webhook: ${{ env.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload: |
          username: "Catalogue graph CI"
          icon_emoji: ":gh-check-failed:"
          text: "*Catalogue graph integration tests failed* \n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
