localstack:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/localstack/localstack:0.10.5"
  environment:
    - SERVICES=sqs
  ports:
    - "4566:4566"
mysql:
  image: "public.ecr.aws/docker/library/mysql:5.6"
  ports:
    - "3307:3306"
  environment:
    - "MYSQL_ROOT_PASSWORD=password"
