[project]
name = "sierra-adapter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "attrs>=26.1.0",
    "boto3>=1.42.93",
    "click>=8.3.2",
    "pyarrow>=25.0.1",
    "pytz>=2026.1.post1",
    "requests>=2.33.1",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "moto>=5.2.3",
    "pytest",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
