
source ~/.env.sh
export COURSIER_DIR=/root/.cache/coursier/v1

# Merge the built cache into the mounted cache (if present)
rsync -ar --mkpath ~/.sbt.image/ ~/.sbt
rsync -ar --mkpath $COURSIER_DIR.image/ $COURSIER_DIR

# -J-Xss: Stack size (used to hold return addresses, function/method call arguments)
# This is by default in the order of KB, we have experienced OOM & Thread allocation exceptions with lower values
# as some services process large structures via recursive algorithms
# -J-Xms: Minimum (and starting) heap size
# -J-Xmx: Maximum heap size
# The Java heap is the amount of memory allocated to applications running in the JVM.
# Setting maximum and minimum heap size is a shortcut to avoid OOM on startup.
# We've determined the value by experimentation (note containers must be provided at least this much memory).
# -J-XX:MaxMetaspaceSize: Sets the amount of memory used to store compilation metadata (by default unbounded)
# Our use of scala & libraries that use macros means this value can cause OOM errors if a maximum is unset
sbt \
  -batch \
  -J-Xss6M \
  -J-Xms4G \
  -J-Xmx4G \
  -J-XX:MaxMetaspaceSize=2G \
  "$@"
[info] welcome to sbt 1.4.1 (Eclipse Adoptium Java 11.0.15)
[info] loading settings for project catalogue-pipeline-build-build-build from metals.sbt ...
[info] loading project definition from /var/lib/buildkite-agent/builds/buildkite-elasticstack-scala-i-056330cea5820d2ed-1/wellcomecollection/catalogue-pipeline/project/project/project
[info] loading settings for project catalogue-pipeline-build-build from metals.sbt ...
[info] loading project definition from /var/lib/buildkite-agent/builds/buildkite-elasticstack-scala-i-056330cea5820d2ed-1/wellcomecollection/catalogue-pipeline/project/project
[success] Generated .bloop/catalogue-pipeline-build-build.json
[success] Total time: 1 s, completed Jan 27, 2023, 10:02:17 AM
[info] loading settings for project catalogue-pipeline-build from build.sbt,metals.sbt,plugins.sbt ...
[info] loading project definition from /var/lib/buildkite-agent/builds/buildkite-elasticstack-scala-i-056330cea5820d2ed-1/wellcomecollection/catalogue-pipeline/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[success] Generated .bloop/catalogue-pipeline-build.json
[info] compiling 3 Scala sources to /var/lib/buildkite-agent/builds/buildkite-elasticstack-scala-i-056330cea5820d2ed-1/wellcomecollection/catalogue-pipeline/project/target/scala-2.12/sbt-1.0/classes ...
[warn] there were 29 feature warnings; re-run with -feature for details
[warn] one warning found
[info] done compiling
[success] Total time: 7 s, completed Jan 27, 2023, 10:02:25 AM
[info] loading settings for project catalogue-pipeline from build.sbt ...
[info] resolving key references (43761 settings) ...
[info] set current project to catalogue-pipeline (in build file:/var/lib/buildkite-agent/builds/buildkite-elasticstack-scala-i-056330cea5820d2ed-1/wellcomecollection/catalogue-pipeline/)
[info] Running in build environment: dev
[info] Installing the s3:// URLStreamHandler via java.net.URL.setURLStreamHandlerFactory
[info] Creating a new Ivy URLHandlerDispatcher to handle s3:// URLs
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 3 Scala sources in batcher:compile ...
[info] Formatting 43 Scala sources in internal_model:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 1 Scala source in flows:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 28 Scala sources in display_model:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
S3URLHandler - Looking up AWS Credentials for bucket: releases.mvn-repo.wellcomecollection.org ...
S3URLHandler - Using AWS Access Key Id: ASIA3B6K4VLAXW2N676I for bucket: releases.mvn-repo.wellcomecollection.org
S3URLHandler - Created S3 Client for bucket: releases.mvn-repo.wellcomecollection.org and region: eu-west-1
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 23 Scala sources in source_model:compile ...
[info] Formatting 12 Scala sources in tei_id_extractor:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 2 Scala sources in tei_adapter:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 7 Scala sources in calm_api_client:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 1 Scala source in source_model_typesafe:compile ...
[info] Formatting 16 Scala sources in reindex_worker:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 7 Scala sources in mets_adapter:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 3 Scala sources in calm_indexer:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 13 Scala sources in sierra_reader:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 11 Scala sources in pipeline_storage:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 6 Scala sources in sierra_linker:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 5 Scala sources in sierra_merger:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 4 Scala sources in calm_adapter:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 5 Scala sources in calm_deletion_checker:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 1 Scala source in pipeline_storage_typesafe:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 14 Scala sources in id_minter:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 18 Scala sources in transformer_common:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 7 Scala sources in sierra_indexer:compile ...
[info] Formatting 2 Scala sources in router:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 4 Scala sources in ingestor_common:compile ...
[info] Formatting 14 Scala sources in matcher:compile ...
[info] Formatting 13 Scala sources in inference_manager:compile ...
[info] Formatting 7 Scala sources in path_concatenator:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 9 Scala sources in transformer_mets:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 11 Scala sources in relation_embedder:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 5 Scala sources in ingestor_works:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 5 Scala sources in ingestor_images:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 14 Scala sources in transformer_calm:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] /var/lib/buildkite-agent/builds/buildkite-elasticstack-scala-i-056330cea5820d2ed-1/wellcomecollection/catalogue-pipeline/pipeline/transformer/transformer_calm/src/main/scala/weco/pipeline/transformer/calm/transformers/CalmTermsOfUse.scala:134: error: illegal start of simple expression
[warn] ).exists {
[warn]       ^
[info] Formatting 24 Scala sources in transformer_miro:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 56 Scala sources in transformer_sierra:compile ...
[warn] /var/lib/buildkite-agent/builds/buildkite-elasticstack-scala-i-056330cea5820d2ed-1/wellcomecollection/catalogue-pipeline/pipeline/transformer/transformer_sierra/src/main/scala/weco/pipeline/transformer/sierra/transformers/SierraLanguages.scala:22: error: illegal start of simple expression
[warn] )
[warn]   ^
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 19 Scala sources in transformer_tei:compile ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Formatting 18 Scala sources in merger:compile ...
[success] Total time: 34 s, completed Jan 27, 2023, 10:03:05 AM
[1mAll done! ✨ 🍰 ✨[0m
67 files left unchanged.[0m
