localstack:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/localstack/localstack:0.10.5"
  environment:
    - SERVICES=sqs
  ports:
    - "4566:4566"
elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.3"
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    - "http.host=0.0.0.0"
    - "transport.host=0.0.0.0"
    - "cluster.name=wellcome"
    - "discovery.type=single-node"

    # This is deliberately much lower than the default (100mb), because we want
    # to test that our code works correctly when it exceeds this limit, but without
    # queuing up 100mb+ of documents in-memory during tests.
    - "http.max_content_length=1mb"
