import argparse
from pathlib import PurePosixPath
from typing import Literal, Self

from pydantic import BaseModel

import config
from models.events import BasePipelineEvent, IncrementalWindow, PipelineIndexDates
from utils.types import IngestorLoadFormat, IngestorType


class IngestorStepEvent(BasePipelineEvent):
    ingestor_type: IngestorType
    job_id: str
    load_format: IngestorLoadFormat = "parquet"

    @property
    def index_date(self) -> str:
        """Return final index date based on ingestor type. Use pipeline date if no index date specified."""
        return getattr(self.index_dates, self.ingestor_type) or self.pipeline_date

    def get_path_prefix(self) -> str:
        """
        Return the S3 path prefix of the event.

        Full reindex mode example (job ID stores an autogenerated timestamp):
        `ingestor_concepts/2025-05-05/2025-06-06/20250930T0930`

        Incremental mode example (job ID corresponds to the processed time window):
        `ingestor_concepts/2025-05-05/2025-06-06/2025-01-01T00:00-2025-01-01T00:15`
        """
        job_id = self.job_id
        if self.window is not None:
            job_id = self.window.to_formatted_string()

        parts: list[str] = [
            f"{config.INGESTOR_S3_PREFIX}_{self.ingestor_type}",
            self.pipeline_date,
            self.index_date,
            job_id,
        ]
        return str(PurePosixPath(*parts))

    def get_s3_uri(self, file_name: str, file_format: str | None = None) -> str:
        prefix = self.get_path_prefix()
        return f"s3://{config.CATALOGUE_GRAPH_S3_BUCKET}/{prefix}/{file_name}.{file_format or self.load_format}"

    @classmethod
    def from_argparser(cls, args: argparse.Namespace) -> Self:
        window = IncrementalWindow.from_argparser(args)

        index_date_works, index_date_concepts = None, None
        if args.ingestor_type == "works":
            index_date_works = args.index_date
        elif args.ingestor_type == "concepts":
            index_date_concepts = args.index_date

        index_dates = PipelineIndexDates(
            merged=args.index_date_merged,
            works=index_date_works,
            concepts=index_date_concepts,
        )
        return cls(**args.__dict__, window=window, index_dates=index_dates)


class IngestorLoaderLambdaEvent(IngestorStepEvent):
    pass_objects_to_index: bool = False


class IngestorIndexerObject(BaseModel):
    s3_uri: str
    content_length: int
    record_count: int


class IngestorIndexerLambdaEvent(IngestorStepEvent):
    objects_to_index: list[IngestorIndexerObject] | None = None


class IngestorIndexerMonitorLambdaEvent(IngestorStepEvent):
    success_count: int


class IngestorDeletionsLambdaEvent(IngestorStepEvent):
    force_pass: bool = False
    ingestor_type: Literal["concepts"] = "concepts"
