import argparse
from pathlib import PurePosixPath
from typing import Self

from pydantic import BaseModel

import config
from models.events import (
    BasePipelineEvent,
    PipelineIndexDates,
)
from utils.types import IngestorDeletionsType, IngestorLoadFormat, IngestorType


class IngestorStepEvent(BasePipelineEvent):
    ingestor_type: IngestorType
    job_id: str
    load_format: IngestorLoadFormat = "parquet"

    @property
    def index_date(self) -> str:
        """Return final index date based on ingestor type. Use pipeline date if no index date specified."""
        return getattr(self.index_dates, self.ingestor_type) or self.pipeline_date

    @property
    def s3_service_prefix_parts(self) -> list[str]:
        return [
            f"{config.INGESTOR_S3_PREFIX}_{self.ingestor_type}",
            f"index-{self.index_date}",
        ]

    def get_path_prefix(self) -> str:
        """
        Return the S3 path prefix of the event.

        Full reindex mode example (job ID stores an autogenerated timestamp):
        `graph-2026-01-01/pipeline-2025-05-05/ingestor_concepts/index-2025-06-06/full/20250930T0930`

        Incremental mode example (job ID corresponds to the processed time window):
        `graph-2026-01-01/pipeline-2025-05-05/ingestor_concepts/index-2025-06-06/windows/20250101T0000-20250101T0015/`
        """
        parts = self.s3_prefix_parts

        if self.window is None and self.ids is None:
            parts.append(self.job_id)

        return str(PurePosixPath(*parts))

    def get_s3_uri(self, file_name: str, file_format: str | None = None) -> str:
        prefix = self.get_path_prefix()
        bucket = config.CATALOGUE_GRAPH_S3_BUCKET
        return f"s3://{bucket}/{prefix}/{file_name}.{file_format or self.load_format}"

    @classmethod
    def from_argparser(cls, args: argparse.Namespace) -> Self:
        base_event = super().from_argparser(args)

        index_date_works, index_date_concepts, index_date_images = None, None, None
        if args.ingestor_type == "works":
            index_date_works = args.index_date
        elif args.ingestor_type == "concepts":
            index_date_concepts = args.index_date
        elif args.ingestor_type == "images":
            index_date_images = args.index_date

        index_dates = PipelineIndexDates(
            merged=getattr(args, "index_date_merged", None),
            augmented=getattr(args, "index_date_augmented", None),
            works=index_date_works,
            concepts=index_date_concepts,
            images=index_date_images,
        )
        return cls(
            **base_event.model_dump(exclude={"index_dates"}), index_dates=index_dates
        )


class IngestorLoaderLambdaEvent(IngestorStepEvent):
    pass_objects_to_index: bool = False


class IngestorIndexerObject(BaseModel):
    s3_uri: str
    content_length: int
    record_count: int


class IngestorIndexerLambdaEvent(IngestorStepEvent):
    objects_to_index: list[IngestorIndexerObject] | None = None


class IngestorIndexerMonitorLambdaEvent(IngestorStepEvent):
    success_count: int


class IngestorDeletionsLambdaEvent(IngestorStepEvent):
    force_pass: bool = False
    ingestor_type: IngestorDeletionsType
