name: "Adapters: Deploy"

on:
  workflow_call:
    inputs:
      deploy_tag:
        description: "Tag to deploy (e.g., commit SHA)"
        required: true
        type: string
    secrets:
      EBSCO_ADAPTER_CI_ROLE_ARN:
        description: "Role ARN to assume for deploying adapter resources"
        required: true
  workflow_dispatch:
    inputs:
      deploy_tag:
        description: "Tag to deploy (e.g., commit SHA)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        adapters:
          [
            {
              3_prefix: lambdas/ebsco_adapter/ebsco_adapter_iceberg,
              lambda_name: ebsco-adapter-trigger,
            }
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-lambda-zip
        with:
          s3_prefix: ${{ matrix.adapters.s3_prefix }}
          lambda_name: ${{ matrix.adapters.lambda_name }}
          deploy_tag: ${{ inputs.deploy_tag }}
          role_to_assume: ${{ secrets.EBSCO_ADAPTER_CI_ROLE_ARN }}
