name: "Adapters: Run checks"
on:
  push:
    branches:
      - main
    paths:
      - "ebsco_adapter/ebsco_adapter_iceberg/**"
      - ".github/workflows/adapter-python-ci.yml"
  pull_request:
    paths:
      - "ebsco_adapter/ebsco_adapter_iceberg/**"
      - ".github/workflows/adapter-python-ci.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  python-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ebsco_adapter/ebsco_adapter_iceberg]
    steps:
      - uses: actions/checkout@v3
      - uses: wellcomecollection/.github/.github/actions/python_check@main
        with:
          folder: ${{matrix.project}}

  build-lambda-zip:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ebsco_adapter/ebsco_adapter_iceberg]
    needs: [python-checks]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-lambda-zip
        with:
          folder: ${{matrix.project}}
          upload_to_s3: true
          s3_bucket: wellcomecollection-platform-infra
          s3_prefix: lambdas/${{matrix.project}}
          s3_tag: ${{ github.sha }}
          role_to_assume: ${{ secrets.EBSCO_ADAPTER_CI_ROLE_ARN }}

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [build-lambda-zip]
    uses: ./.github/workflows/adapter-python-deploy.yml
    with:
      deploy_tag: ${{ github.sha }}
    secrets:
      EBSCO_ADAPTER_CI_ROLE_ARN: ${{ secrets.EBSCO_ADAPTER_CI_ROLE_ARN }}
