# Runs auto-formatting script on push to any branch
name: "Scala auto-formatting"

on: push

permissions:
  id-token: write
  contents: write

jobs:
  autoformat:
    uses: wellcomecollection/.github/.github/workflows/scala_formatting.yml@main
    secrets: inherit

  # TO DO add sbt warnings report from .reports/scalafmt.out
