name: "Catalogue graph: Run CI pipeline"

on:
  push:
    branches:
      - main
    paths: "catalogue_graph/**"
  pull_request:
    paths: "catalogue_graph/**"

permissions:
  contents: read
  id-token: write

jobs:
  python-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wellcomecollection/.github/.github/actions/python_check@main
        with:
          folder: catalogue_graph

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install UV
        run: pip install uv
      - name: Install dependencies
        run: |
          cd catalogue_graph
          uv sync
      - name: Run typecheck
        run: |
          ./catalogue_graph/scripts/typecheck.sh

  autoformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install UV
        run: pip install uv
      - name: Install dependencies
        run: |
          cd catalogue_graph
          uv sync
      - name: Run autoformat check
        run: |
          ./catalogue_graph/scripts/autoformat.sh --check

  build:
    runs-on: ubuntu-latest
    needs: [python-checks, typecheck, autoformat]
    if: ${{ needs.python-checks.result == 'success' && needs.typecheck.result == 'success' && needs.autoformat.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.CATALOGUE_GRAPH_CI_ROLE_ARN }}
      - name: Log in to private ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build artefacts
        run: |
          ./catalogue_graph/scripts/build.sh

  push:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.CATALOGUE_GRAPH_CI_ROLE_ARN }}
      - name: Log in to private ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Push artefacts
        run: |
          ./catalogue_graph/scripts/build.sh --push

  deploy:
    runs-on: ubuntu-latest
    needs: push
    if: ${{ needs.push.result == 'success' }}
    strategy:
      matrix:
        lambda_name:
          [
            catalogue-graph-bulk-loader,
            catalogue-graph-bulk-load-poller,
            catalogue-graph-indexer,
            catalogue-graph-remover,
            catalogue-graph-ingestor-trigger,
            catalogue-graph-ingestor-trigger-monitor,
            catalogue-graph-ingestor-loader,
            catalogue-graph-ingestor-loader-monitor,
            catalogue-graph-ingestor-indexer,
            catalogue-graph-ingestor-indexer-monitor,
            catalogue-graph-ingestor-deletions,
            catalogue-graph-ingestor-reporter,
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.CATALOGUE_GRAPH_CI_ROLE_ARN }}
      - name: Deploy ${{ matrix.lambda_name }} lambda
        run: |
          ./catalogue_graph/scripts/deploy_lambda_zip.sh ${{ matrix.lambda_name }}
