name: "Catalogue graph: Run CI pipeline"

on:
  push:
    branches:
      - main
    paths:
      - "catalogue_graph/**"
      - ".github/workflows/catalogue-graph-ci.yml"
  pull_request:
    paths:
      - "catalogue_graph/**"
      - ".github/workflows/catalogue-graph-ci.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  python-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wellcomecollection/.github/.github/actions/python_check@main
        with:
          folder: catalogue_graph

  build-lambda-zip:
    runs-on: ubuntu-latest
    needs: [python-checks]
    if: ${{ needs.python-checks.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.CATALOGUE_GRAPH_CI_ROLE_ARN }}
      - name: Build lambda ZIP artefact
        run: |
          ./catalogue_graph/scripts/build.sh --skip-container-build

  build-extractor-image:
    runs-on: ubuntu-latest
    needs: [python-checks]
    if: ${{ needs.python-checks.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: wellcomecollection/.github/.github/actions/docker-build-and-push@main
        with:
          registry: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome
          folder: catalogue_graph
          target: catalogue_graph_extractor
          tag: ${{ github.sha }}
          role_to_assume: ${{ secrets.CATALOGUE_GRAPH_CI_ROLE_ARN }}
          publish_latest: ${{ github.ref == 'refs/heads/main' }}

  push-lambda-zip:
    runs-on: ubuntu-latest
    needs: build-lambda-zip
    if: ${{ needs.build-lambda-zip.result == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.CATALOGUE_GRAPH_CI_ROLE_ARN }}
      - name: Push lambda ZIP artefact
        run: |
          ./catalogue_graph/scripts/build.sh --skip-container-build --push
