name: "Catalogue graph: Run CI pipeline"

on:
  push:
    branches:
      - main
    paths:
      - "catalogue_graph/**"
      - ".github/workflows/catalogue-graph-ci.yml"
  pull_request:
    paths:
      - "catalogue_graph/**"
      - ".github/workflows/catalogue-graph-ci.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  python-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wellcomecollection/.github/.github/actions/python_check@main
        with:
          folder: catalogue_graph

  build-extractor-image:
    runs-on: ubuntu-latest
    needs: [python-checks]
    steps:
      - uses: actions/checkout@v3
      - uses: wellcomecollection/.github/.github/actions/docker-build-and-push@main
        with:
          registry: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome
          folder: catalogue_graph
          target: catalogue_graph_extractor
          tag: ${{ github.sha }}
          role_to_assume: ${{ secrets.CATALOGUE_GRAPH_CI_ROLE_ARN }}
          publish_latest: ${{ github.ref == 'refs/heads/main' }}

  build-unified-pipeline-image:
    runs-on: ubuntu-latest
    needs: [python-checks]
    steps:
      - uses: actions/checkout@v3
      - uses: wellcomecollection/.github/.github/actions/docker-build-and-push@main
        with:
          registry: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome
          folder: catalogue_graph
          target: unified_pipeline_lambda
          dockerfile: lambda.Dockerfile
          tag: ${{ github.sha }}
          role_to_assume: ${{ secrets.CATALOGUE_GRAPH_CI_ROLE_ARN }}
          publish_latest: ${{ github.ref == 'refs/heads/main' }}

  # Temporarily add this here for testing
  deploy-dated-unified-pipeline-lambdas:
    name: Deploy dated unified pipeline lambdas
    runs-on: ubuntu-latest
    needs: [build-unified-pipeline-image]
    strategy:
      matrix:
        component:
          - transformer_ebsco
    steps:
      - uses: actions/checkout@v3
      - name: Deploy dated pipeline lambda (latest)
        uses: ./.github/actions/deploy-dated-pipeline-lambda
        with:
          source_tag: ${{ github.sha }}
          registry: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome
          image_name: unified_pipeline_lambda
          role_to_assume: ${{ secrets.CATALOGUE_GRAPH_CI_ROLE_ARN }}
          aws_region: eu-west-1
          lambda_suffix: ${{ matrix.component }}

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [build-extractor-image, build-unified-pipeline-image]
    uses: ./.github/workflows/catalogue-graph-deploy.yml
    with:
      deploy_tag: ${{ github.sha }}
    secrets:
      CATALOGUE_GRAPH_CI_ROLE_ARN: ${{ secrets.CATALOGUE_GRAPH_CI_ROLE_ARN }}
