# .github/workflows/dependency-graph.yml
name: Update Dependency Graph
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-submission@v2
