name: "Inferrers: Run checks and build"
on: [ push ]
# paths: [ 'pipeline/inferrer/**' ]

permissions:
  contents: read
  id-token: write

jobs:
  python-inferrers-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ aspect_ratio_inferrer, feature_inferrer, palette_inferrer ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python_check
        with:
          folder: pipeline/inferrer/${{matrix.project}}
  python-inferrers-builds:
    strategy:
      matrix:
        project: [ aspect_ratio_inferrer, feature_inferrer, palette_inferrer ]
    uses: ./.github/workflows/python-docker.yml
    with:
      folder: pipeline/inferrer
      target: ${{matrix.project}}
      tag: ${{github.sha}}
    secrets:
      role-to-assume: ${{secrets.GHA_ECR_PUSH_ROLE_ARN}}