on:
  push:
    paths: [ 'pipeline/inferrer/**' ]
jobs:
  python-inferrers-checks:
    strategy:
      matrix:
        project: [ aspect_ratio_inferrer, feature_inferrer, palette_inferrer ]
    uses: actions/python-check.yml
    with:
      folder: pipeline/inferrer/${{matrix.project}}