on:
  push:
    paths: [ 'pipeline/inferrer/**' '.github' ]
  workflow_dispatch:
jobs:
  python-inferrers-checks:
    strategy:
      matrix:
        project: [ aspect_ratio_inferrer, feature_inferrer, palette_inferrer ]
    uses: ./.github/workflows/python-check.yml
    with:
      folder: pipeline/inferrer/${{matrix.project}}