name: "Inferrers: Run checks and build"
on: [ push ]
# paths: [ 'pipeline/inferrer/**' ]

permissions:
  contents: read
  id-token: write

jobs:
  python-inferrers-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ aspect_ratio_inferrer, feature_inferrer, palette_inferrer ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python_check
        with:
          folder: pipeline/inferrer/${{matrix.project}}
  python-inferrers-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ aspect_ratio_inferrer, feature_inferrer, palette_inferrer ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-docker
        with:
          folder: pipeline/inferrer
          target: ${{matrix.project}}
          tag: ${{github.sha}}
          role_to_assume: ${{secrets.GHA_ECR_PUSH_ROLE_ARN}}