name: "Inferrers: Run checks and build"
on: [ workflow_dispatch, push ]
# paths: [ 'pipeline/inferrer/**' ]
jobs:
  python-inferrers-checks:
    strategy:
      matrix:
        project: [ aspect_ratio_inferrer, feature_inferrer, palette_inferrer ]
    uses: ./.github/workflows/python-check.yml
    with:
      folder: pipeline/inferrer/${{matrix.project}}
  python-inferrers-builds:
    strategy:
      matrix:
        project: [ aspect_ratio_inferrer, feature_inferrer, palette_inferrer ]
    uses: ./.github/workflows/python-docker.yml
    with:
      folder: pipeline/inferrer
      target: ${{matrix.project}}
      tag: ${{github.sha}}
      role-to-assume: ${{secrets.GHA_ECR_PUSH_ROLE_ARN}}