name: "Python check"
# TODO: This belongs in .github repo
on:
  workflow_call:
    inputs:
      folder:
        type: string
        required: true
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    name: Lint and test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version-file: ${{ inputs.folder}}/.python-version
      - name: setup dependencies
        run: |
          pip install uv
          uv sync --all-groups
        working-directory: ${{inputs.folder}}
      - name: lint
        run: uvx ruff check  ${{inputs.folder}}
      - name: test
        id: test
        run: |
          set +e
          uv run pytest
          TEST_OUTPUT=$?
          # 5 = No Tests Run.  Ideally, this would be a failure, but we 
          # do have some projects with no tests, where it is still beneficial
          # to "run the tests", as that proves that the code can be run.
          if [[ TEST_OUTPUT -eq 5 ]]; then TEST_OUTPUT=0; fi
          exit $TEST_OUTPUT
        working-directory: ${{inputs.folder}}
