FROM eclipse-temurin:11-jre

LABEL maintainer = "Wellcome Collection <digital@wellcomecollection.org>"

RUN apt-get update && apt-get install -y bash && rm -rf /var/lib/apt/lists/*

ADD target/universal/stage /opt/docker

ENTRYPOINT ["/opt/docker/bin/transformer_mets"]
